import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import './DevTools.css';
export const DevTools = () => {
    const link = 'https://github.com/guocaoyi/create-chrome-ext';
    return (_jsxs("main", { children: [_jsx("h3", { children: "DevTools Page" }), _jsx("a", { href: link, target: "_blank", children: "generated by create-chrome-ext" })] }));
};
export default DevTools;
