import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState, useEffect } from 'react';
import './NewTab.css';
export const NewTab = () => {
    const getTime = () => {
        const date = new Date();
        const hour = String(date.getHours()).padStart(2, '0');
        const minute = String(date.getMinutes()).padStart(2, '0');
        return `${hour}:${minute}`;
    };
    const [time, setTime] = useState(getTime());
    const link = 'https://github.com/guocaoyi/create-chrome-ext';
    useEffect(() => {
        let intervalId = setInterval(() => {
            setTime(getTime());
        }, 1000);
        return () => {
            clearInterval(intervalId);
        };
    }, []);
    return (_jsxs("section", { children: [_jsx("span", {}), _jsx("h1", { children: time }), _jsx("a", { href: link, target: "_blank", children: "generated by create-chrome-ext" })] }));
};
export default NewTab;
